# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  -
    goos:
      - windows
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - plan9
    env:
      - CGO_ENABLED=0
archive:
  format: zip
  replacements:
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  # Fuck Github
  disable: true

# nfpm:
#   license: Unlicense
#   homepage: https://git.dtluna.net/dtluna/syncthing-cli
#   description: CLI client for Syncthing in Go
#   vendor: dtluna
#   maintainer: dtluna <dtluna@waifu.club>
#   formats:
#     - deb
#     - rpm
