project_name: syncthing-cli
build:
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goos:
    - windows
    - linux
    - darwin
    # TODO: Enable these when xdg gets a new release
    # - openbsd
    # - freebsd
archives:
- replacements:
    openbsd: OpenBSD
    freebsd: FreeBSD
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  gitea:
    owner: dtluna
    name: syncthing-cli
gitea_urls:
  api: https://git.dtluna.net/api/v1/
env_files:
  gitea_token: ~/.config/goreleaser/gitea_token
